language: python

services:
  - docker

jobs:
  include:
  - env: IMAGE=fedora TAG=32
  # - env: IMAGE=debian TAG=10

install: docker pull ${IMAGE}:${TAG}

script:
  - export VERSION=$(cat VERSION)
  - docker run -e VERSION=$VERSION -v $(pwd):/libreeye-${VERSION} ${IMAGE}:${TAG} /libreeye-${VERSION}/scripts/build-${IMAGE}.sh

before_deploy:
  - mkdir github_deploy/
  - cp $(find . -name '*.noarch.rpm') github_deploy/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: github_deploy/*
  skip_cleanup: true
  on:
    tags: true


branches:
  only:
    - master
    - dev
    - /^[\d.]+$/

git:
  depth: false
