language: python

python:
  - "3.7"

before-install: python -m pip install --upgrade pip

install: python -m pip install twine wheel

script: python setup.py sdist bdist_wheel

branches:
  only:
    - master

deploy:
  skip_cleanup: true
  provider: pypi
  user: "__token__"
  password: "$PYPI_TOKEN"
  distributions: "sdist bdist_wheel"