# Recording options
recorder:
  # URL of the IP camera stream
  camera: 'rtsp://192.168.0.123:554/user=admin&password=&channel=1&stream=0.sdp?real_stream'
  # Timeout, in seconds, to wait for frames from the camera before attempting to reconnect
  timeout: 30
  # Reconnection attempts
  reconnect_attempts: 3
  # Base delay between reconnection attempts in seconds. The delay grows exponentially between successive attempts.
  reconnect_base_delay: 10
  # Number of frames to buffer before passing them into the sinks
  buffer_size: 10
# Storage options
storage:
  # Local storage options
  local:
    # Path in which to store all recordings
    path: /mnt/drive
    # Duration of each recording, in minutes
    segment_length: 30
    # Days to keep the recordings
    days: 30
  # AWS S3 storage options
  aws:
    # AWS credentials
    aws_access_key_id: key
    aws_secret_access_key: secret
    # Size of the fragments sent to the S3 bucket, in MB
    part_min_size: 5
    # Timeout in seconds
    timeout: 5
    # Name of the S3 bucket
    bucket: my_bucket
    # Path in which to store all recordings
    path: example_camera/
    # Duration of each recording, in minutes
    segment_length: 30
    # Days to keep the recordings
    days: 10
# Logging options
log:
  # Name of the log file
  file: camera.log
  # Print logs on console as well
  console: true
  # Level of the log messages (debug or info)
  level: info